name: ⚡ ARIZAK-MD WhatsApp Bot

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm install

      - name: ⚡ Run ARIZAK-MD
        env:
          SESSION_ID: ${{ starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkIxcUNSV3d4UGxNTVRxTk9xdlB0YmxoRUFDNHFJdmovZ0NCdGV6KzMybz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0N0K3o4ZjdXUUMvN2pCcDQ5Ymc1QVg5TnFWOXA4VHBDYXJJNWR2ZFZBQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpTkxvdkVQdW5wZnVoRkpXNFlBYmJMZGZiQ1RaUXdrL29mU0Z0Zm0rem5RPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJOdVZDazFPdnUyanBxTDBoTzI2TUZ1TkdwbmNJT1BVZDk0Sk5Rb3BUV1I4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZHRkhQbjY0YmRzdVFvVWY5ei9FNmJuN0VqN0VNb1pnZmlZaXZjU2tyVWc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imw4VktwR0ZaWFJ5MzYwczJzMTU0VEM0ekVZaUlidHYzZ1oyU1h3ZUJvRDQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0tVYW11ai9yanQvZTJQTEJVbGlJbDdwL2hQWDFNMG1FU1FjRll2N0trUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUjY5NGVjQldSRVZNM1V6Y1lJc0FRQUhzeDg5aTkvOG1ocDFMMk5vNGNYWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZQdTl6QWYxSVhBNG9NZVp6b1B2SGVTODM1OXJMc0FjakFVL3FMZmN0TW1JTGlTTnlWS2VRbzd6bXFEUEVZM21hOSswT2dUOWFyS3RBZXg3NThUb0RRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjYsImFkdlNlY3JldEtleSI6ImtMVjJsNmVtZUNMejI4WlFSemVvQlVvTzZYTmI4dUt6NU14QllqVGhVRmM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkdOWkNYTVhIIiwibWUiOnsiaWQiOiIyNTQ3Mjc3NDAzODk6MTZAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiYWJkaXJpaSIsImxpZCI6IjIzMjA5NjI0MTAzNzM2MToxNkBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pHSTI2d0RFTnp1cHNVR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImJNVlJrZ0JCTlNiNUNhaVZFbmY5d1dvejdtV0VYWFVuckphSHJnL3NpRXc9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImEyVlBjZ2NpYU15TGk5TzZhSDVQSjFtaDRMMlNxbzI2TnIyTXVUa3RLY1dhMTBFdXpCZS8wREw3WVZhOU5WeHgvdWU2NnNFSldEWFNLek1oK0hLV0RRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiI1eWVNSkE5dWNtT3hOeXQwcS9oWWpKSFo3ZVZUa0dHUmVoWWVaM1lJYTdZM2xiaVVMamxTTlZ4cTVENTBpeERJUkRBKzRXa3Z6aEsrME0rRUViRi9CUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDcyNzc0MDM4OToxNkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJXekZVWklBUVRVbStRbW9sUkozL2NGcU0rNWxoRjExSjZ5V2g2NFA3SWhNIn19XSwicGxhdGZvcm0iOiJzbWJhIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQTBJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTU5NTMwMDIsImxhc3RQcm9wSGFzaCI6IjJWNzdxVSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT0p1In0= }}
          OWNER_NUMBER: ${{ secrets.254727740389 }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: |
          echo "🚀 Starting ARIZAK-MD..."
          npm start
